springdoc:
  swagger-ui:
    path: /api-test  # swagger-ui ?? ??? ?? ??, ?? ??? ???? http://localhost:8080/swagger-ui/index.html? ????? ?.

    groups-order: DESC # path, query, body, response ??? ??

  paths-to-match:
    - /api/** # swagger-ui? ??? api? ????? ??