spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000

  config:
    import: optional:file:.env[.properties]

  jpa:
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect #dialect를 어떤 것을 쓸 것인지 명시적으로 표기

  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        bucket: ${S3_BUCKET_NAME}
      region:
        static: ap-northeast-2

app:
  s3:
    combos-prefix: combos/v1
    presign-ttl-seconds: 300
    fallback-key: combos/v1/default.png


springdoc:
  swagger-ui:
    path: /api-test  # swagger-ui 접속 주소를 추가, http://localhost:8080/swagger-ui/index.html로 리다이렉션.

    groups-order: DESC # path, query, body, response 순서

  paths-to-match:
    - /api/** # swagger-ui api ui 형식


jwt:
  secret: ${JWT_SECRET}
  expire_ms: ${JWT_EXPIRE_MS:86400000}
  refresh_expire_ms: ${JWT_REFRESH_EXPIRE_MS:1209600000}